CREATE TABLE Pays (codPays TEXT PRIMARY KEY, nomPays TEXT NOT NULL);
CREATE TABLE Types (id INTEGER PRIMARY KEY, type TEXT NOT NULL);
CREATE TABLE Forets (
    idTyp INTEGER NOT NULL REFERENCES Types(id),
    codP TEXT NOT NULL REFERENCES Pays(codPays),
    superficie REAL NOT NULL
);
INSERT INTO Pays VALUES ('BRA', 'Brésil');
INSERT INTO Pays VALUES ('CNG', 'Congo');
INSERT INTO Pays VALUES ('RUS', 'Russie');
INSERT INTO Pays VALUES ('CAN', 'Canada');
INSERT INTO Pays VALUES ('IDN', 'Indonésie');
INSERT INTO Pays VALUES ('PER', 'Pérou');
INSERT INTO Pays VALUES ('COL', 'Colombie');
INSERT INTO Pays VALUES ('GAB', 'Gabon');
INSERT INTO Pays VALUES ('FRA', 'France');
INSERT INTO Pays VALUES ('MAR', 'Maroc');
INSERT INTO Types VALUES (17, 'Tropicale');
INSERT INTO Types VALUES (38, 'Boréale');
INSERT INTO Types VALUES (29, 'Tempérée');
INSERT INTO Types VALUES (14, 'Méditerranéenne');
INSERT INTO Types VALUES (25, 'Subtropicale');
INSERT INTO Forets VALUES (17, 'BRA', 5500000);
INSERT INTO Forets VALUES (17, 'CNG', 3700000);
INSERT INTO Forets VALUES (38, 'RUS', 7700000);
INSERT INTO Forets VALUES (38, 'CAN', 3000000);
INSERT INTO Forets VALUES (17, 'IDN', 920000);
INSERT INTO Forets VALUES (17, 'PER', 700000);
INSERT INTO Forets VALUES (17, 'COL', 600000);
INSERT INTO Forets VALUES (17, 'GAB', 220000);
INSERT INTO Forets VALUES (29, 'FRA', 170000);
INSERT INTO Forets VALUES (29, 'CAN', 260000);
INSERT INTO Forets VALUES (14, 'MAR', 90000);
INSERT INTO Forets VALUES (25, 'IDN', 300000);
